Bootstrap: docker

From: rocker/tidyverse

%files
    init.sh /init.sh

%environment
    export CONDA_DIR=/opt/mambaforge
    export CONDA_EXE=/opt/mambaforge/bin/conda
    export CONDA_PREFIX_1=$CONDA_DIR
    export RETICULATE_CONDA=$CONDA_EXE

%post
    echo "lock-type=linkbased" > /etc/rstudio/file-locks
    chmod 755 /init.sh
    wget --no-hsts --quiet https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O /tmp/mambaforge.sh && \
    export CONDA_DIR=/opt/mambaforge
    /bin/bash /tmp/mambaforge.sh -b -p ${CONDA_DIR} && \
    rm /tmp/mambaforge.sh && \
    export PATH=${CONDA_DIR}/bin:${PATH}
    . ${CONDA_DIR}/etc/profile.d/conda.sh && conda activate base && \
    conda clean -tipsy && \
    find ${CONDA_DIR} -follow -type f -name '*.a' -delete && \
    find ${CONDA_DIR} -follow -type f -name '*.pyc' -delete && \
    conda clean -afy && \
    mamba install -c conda-forge -c bioconda \
        cmake cython cytoolz psutil h5py pyarrow llvmlite numpy scipy \
        numba numexpr numcodecs networkx python-igraph pytables pandas \
        statsmodels scikit-learn umap-learn hdbscan leidenalg fa2 \
        fit-sne pyfit-sne multicore-tsne seaborn upsetplot pygraphviz pydot \
        joblib snakemake pip && \
    ${CONDA_DIR}/bin/pip3 install radian beni flit trimap dabest hidef \
    truncated_normal decoupler rpy2 anndata2ri scgen scvelo squidpy \
    cellrank bbknn harmonypy kb-python ffq gget gprofiler-official
